if: (branch = master || branch =~ /^v\d+\.\d+\.x$/)

language: rust
rust:
  - stable
os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - llvm-dev
      - libclang-dev
      - clang
  homebrew:
    packages:
      - llvm

before_install:
  - rustup component add rustfmt

script:
  - cargo build -v
  - find target/debug/build -path "*/libuv-sys-*/output" -exec cat '{}' \;
  - cargo test

jobs:
  include:
    - stage: "prepare new libuv version"
      if: branch = master && env(LIBUV_TAG_URL) =~ /^https:\/\/github.com\/libuv\/libuv\/releases\/tag\/v\d+\.\d+\.\d+/
      os: linux
      language: bash
      before_install:
        - echo "Preparing a build for a new version of libuv..."
      script:
        - git config --local user.name $GIT_USER_NAME
        - git config --local user.email $GIT_USER_EMAIL
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/bmatcuk/libuv-sys.git
        - '[[ "$LIBUV_TAG_URL" =~ https://github.com/libuv/libuv/releases/tag/(v[0-9]+.[0-9]+.[0-9]+) ]]'
        - export LIBUV_VERSION="${BASH_REMATCH[1]}"
        - export LIBUV_MAJ_MIN="${LIBUV_VERSION%.*}"
        - export LIBUV_SYS_BRANCH="${LIBUV_MAJ_MIN}.x"
        - export LIBUV_SYS_PREV_VER=$(git tag | grep -q "${LIBUV_MAJ_MIN}." && git tag | grep "${LIBUV_MAJ_MIN}." | sort -V | tail -n 1 || { echo $LIBUV_VERSION; git tag; } | sort -V | grep -B1 "$LIBUV_VERSION" | head -n 1)
        - export LIBUV_SYS_NEXT_VER=$(git tag | grep -q "${LIBUV_MAJ_MIN}." && [[ "$LIBUV_SYS_PREV_VER" =~ .([0-9]+)$ ]] && echo "${LIBUV_MAJ_MIN}.$(( "${BASH_REMATCH[1]}" + 1 ))" || echo "${LIBUV_MAJ_MIN}.0")
        - 'echo "libuv version: $LIBUV_VERSION"'
        - 'echo "libuv maj.min: $LIBUV_MAJ_MIN"'
        - 'echo "libuv-sys branch: $LIBUV_SYS_BRANCH"'
        - 'echo "libuv-sys prev ver: $LIBUV_SYS_PREV_VER"'
        - 'echo "libuv-sys next ver: $LIBUV_SYS_NEXT_VER"'
        - git branch | grep -q "$LIBUV_SYS_BRANCH" && git checkout "$LIBUV_SYS_BRANCH" || git checkout -b "$LIBUV_SYS_BRANCH" "$LIBUV_SYS_PREV_VER"
        - '{ pushd libuv; git checkout "$LIBUV_VERSION"; popd; }'
        - sed -i -e '/^version =/s/".*"/"'"${LIBUV_SYS_NEXT_VER#v}"'"/' Cargo.toml
        - sed -i -e '/^static LIBUV_VERSION:/s/".*"/"'"${LIBUV_SYS_NEXT_VER%.*}"'"/' build.rs
        - git add Cargo.toml build.rs libuv
        - git commit -m "Preparing build for libuv $LIBUV_VERSION"
        - git push --all
    - stage: publish
      if: type = push && fork = false && branch =~ /^v\d+\.\d+\.x$/ && env(LIBUV_TAG_URL) IS blank
      os: linux
      language: bash
      before_install: echo "Preparing to publish release..."
      script: echo "Publishing release..."
      before_deploy:
        - git config --local user.name $GIT_USER_NAME
        - git config --local user.email $GIT_USER_EMAIL
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/bmatcuk/libuv-sys.git
        - export TRAVIS_TAG=$(grep 'version =' Cargo.toml | awk -F'"' '{print "v" $2}')
        - export PREV_TAG=$({ echo $TRAVIS_TAG; git tag; } | sort -V | grep -B1 $TRAVIS_TAG | head -n 1)
        - export LIBUV_VERSION=$({ cd libuv; git describe --tags; })
        - export LIBUV_TAG="libuv-${LIBUV_VERSION}"
        - '{ echo -e "Corresponds to libuv ${LIBUV_VERSION}.\n\n## Changelog\n\n"; git log --pretty=format:"%h %s" "${PREV_TAG}.." 2>/dev/null; } > RELEASELOG.md || true'
        - git tag $LIBUV_TAG
        - git tag -a $TRAVIS_TAG -m "Corresponds to libuv ${LIBUV_VERSION}"
        - git push --tags
      deploy:
        - provider: releases
          file: README.md
          release_notes_file: RELEASELOG.md
          edge: true
          on:
            all_branches: true

stages:
  - "prepare new libuv version"
  - name: test
    if: env(LIBUV_TAG_URL) IS blank
  - publish
