[package]
name = "libuv-sys"
links = "uv"
version = "1.30.0"
description = "Thin FFI bindings for libuv"
categories = ["command-line-interface", "external-ffi-bindings"]
keywords = ["events", "libevent", "loop"]
readme = "README.md"
license = "MIT OR Apache-2.0"
license-file = "LICENSE"
authors = ["Bob Matcuk <bmatcuk@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.51"
cc = "1.0"
pkg-config = "0.3.17"
