name: Check For New Version

on:
  schedule:
    - cron: '42 10 * * *'
  workflow_dispatch:

jobs:
  getversion:
    name: Check For New Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Script
        id: check
        shell: bash
        run: scripts/check-version.sh

  prepare:
    name: Prepare New Version
    needs: getversion
    uses: bmatcuk/libuv-sys/.github/workflows/prepare-new-libuv-version.yml@master
    with:
      version: ${{ needs.getversion.outputs.version }}
    secrets: inherit
